### PR TITLE
Rework mainframe and make everything work together

### LINKED ISSUE #154: Code cleanup in Mainframe

### PR DESCRIPTION
**Pull request by profiluefter**
Ma segt wos

Closes #154

### CODE REVIEW

**Review by EinboeckFranz — APPROVED** [review]
Schaut guad aus

**Review by littlegamer757 — APPROVED** [review]
I do not approve of owning this code

**Comment by profiluefter** [comment]
> I do not approve of owning this code

@littlegamer757 deafst glei fia dei team a ticket erstoin fia [de pfuscherei behebn](https://github.com/htl-grieskirchen-core/core/pull/155/files#diff-fc9ffdad86d5f1d03027e0d7778117ded74eb9b527b1b07cfe83a196b1685546R12), a wenns copilot goaned so schiach gmocht hod

**Review by Klausmd5 — APPROVED** [review]
Schaut brauchboara aus ois vorher

**Pull request merged**
