### PR TITLE
Feature/auto deploy update builder dings hüfe

### PR DESCRIPTION
**Pull request by Klausmd5**

### CODE REVIEW

**Comment by Klausmd5** [comment]
haut hi. 
image

**Comment by Klausmd5** [comment]
olles online. gema

**Comment by profiluefter** [comment]
gonz sche is des nu ned weil de url dera generiert hod koa protokoll dabei, oda @Klausmd5

**Comment by littlegamer757** [comment]
\> implements auto deploy update builder dings hüfe
\> creates a pull request to merge changes into develop
\> requests a review from other project members
\> merges changes before they are approved
\> refuses to elaborate
\> leaves

classic synopsis code quality enjoyer

**Comment by littlegamer757** [comment]
i moan passt eh, oba hobe witzig gfundn

**Comment by CallMeAlasca** [comment]
Also SYP teachers: moch ma hoid koa Review mehr, waun des so laung dauert.

**Comment by Klausmd5** [comment]
> gonz sche is des nu ned weil de url dera generiert hod koa protokoll dabei, oda @Klausmd5

Doch solang des mainframe und ds plugin am söbm renan scho

**Comment by profiluefter** [comment]
ajo stimmt, hätt ma docht bei origin is as protokoll ned dabei
grafik

**Pull request merged**
